imports:
    - { resource: parameters.yml }

framework:
  secret:     %secret%
  profiler:
    enabled:  %kernel.debug%

doctrine:
  dbal:
    driver:   %database_driver%
    host:     %database_host%
    port:     %database_port%
    dbname:   %database_name%
    user:     %database_user%
    password: %database_password%
    charset:  UTF8

  orm:
    auto_mapping: true
    auto_generate_proxy_classes: %kernel.debug%
